name: Frontend CD

on: 
  push:
    branches: [devel, stage, prod]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    env:
        APP_BUCKET: ${{format('{0}-v1-fullstack-jmq-app', github.ref_name)}}

    steps: 
        - name: Check out code
          uses: actions/checkout@v3

        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '15'

        - name: Install dependencies
          run: npm install

        - name: Build project
          run: npm run build

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-region: us-east-1
            role-to-assume: ${{secrets.AWS_ROLE_ARN}}

        - name: Upload to S3
          run: aws s3 sync build/ s3://$APP_BUCKET --delete