name: Frontend CI

on: 
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps: 
        - name: Check out code
          uses: actions/checkout@v3

        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
           node-version: '15'

        - name: Install dependencies
          run: npm install

        - name: Run linter
          run: npm run lint

        - name: Run formatter
          run: npm run prettier --write

        - name: Run tests
          run: CI=true npm run test

        - name: Build project
          run: npm run build